version: "3.7"

services:
  app:
    build:
      args:
        user: ewastepas
        uid: 1002
      context: ./
      dockerfile: Dockerfile
    image: ewastepas-admin-api
    container_name: ewastepas-admin-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ewastepas-bridge
    ports:
      - 8031:8000

networks:
  ewastepas-bridge:
    external: true
